_target_: src.datamodules.mnist_datamodule.MNISTDataModule

datasets:
  data_dir: ${paths.data_dir}
  train_val_test_split: [55_000, 5_000, 10_000]
  seed: 42

transforms:
  train:
    order: ["normalize"]
    normalize:
      _target_: albumentations.Normalize
      mean: [0.1307]
      std: [0.3081]
      p: 1.0

  valid_test:
    order: ["normalize"]
    normalize:
      _target_: albumentations.Normalize
      mean: [0.1307]
      std: [0.3081]
      p: 1.0

loaders:
  train:
    batch_size: 128
    shuffle: True
    num_workers: 0
    drop_last: True
    pin_memory: False

  valid:
    batch_size: 128
    shuffle: False
    num_workers: 0
    drop_last: False
    pin_memory: False

  test:
    batch_size: 128
    shuffle: False
    num_workers: 0
    drop_last: False
    pin_memory: False

  predict:
    batch_size: 128
    shuffle: False
    num_workers: 0
    drop_last: False
    pin_memory: False
